//! A file-explorer experience: an expandable [`Tree`] of the project, a
//! live [`Breadcrumb`] of the selection's path, a preview pane
//! ([`Paragraph`] for files / [`DescriptionList`] for folders), and a
//! [`StatusBar`]. `↑/↓` select, `Enter` expands a folder or opens a file.

use rstui_core::{Constraint, KeyCode, Layout, Line, Margin, Position, Rect, Style};
use rstui_runtime::Frame;
use rstui_widgets::{
    Block, BorderType, Breadcrumb, DescriptionList, DescriptionRow, Paragraph, StatusBar, Tree,
    TreeItem, Wrap,
};

use crate::screens::ScreenOutcome;
use crate::theme::Theme;

/// One filesystem entry.
struct Node {
    depth: u16,
    name: &'static str,
    dir: bool,
    /// For files: a size label and a preview body.
    size: &'static str,
    body: &'static str,
}

const fn d(depth: u16, name: &'static str) -> Node {
    Node {
        depth,
        name,
        dir: true,
        size: "—",
        body: "",
    }
}
const fn f(depth: u16, name: &'static str, size: &'static str, body: &'static str) -> Node {
    Node {
        depth,
        name,
        dir: false,
        size,
        body,
    }
}

const TREE: [Node; 11] = [
    d(0, "crates"),
    d(1, "rstui-kitchen-sink"),
    d(2, "src"),
    f(
        3,
        "lib.rs",
        "14 KB",
        "//! rstui-kitchen-sink — one interactive App.\npub(crate) mod chrome;\npub(crate) mod screens;\npub struct KitchenSink { /* … */ }",
    ),
    f(
        3,
        "chrome.rs",
        "9 KB",
        "//! Header, rail, status bar, overlays.\npub(crate) fn view_sidebar(..) { /* … */ }",
    ),
    d(3, "screens"),
    f(
        4,
        "chat.rs",
        "8 KB",
        "//! A chat / messenger experience.\nfn canned_reply(body: &str) -> String { /* … */ }",
    ),
    f(
        4,
        "mod.rs",
        "11 KB",
        "//! Screen dispatch.\npub(crate) enum Screen { /* 18 */ }",
    ),
    f(
        2,
        "Cargo.toml",
        "0.5 KB",
        "[package]\nname = \"rstui-kitchen-sink\"\npublish = false",
    ),
    f(
        1,
        "README.md",
        "44 KB",
        "# rstui\nAn idiomatic Rust TUI framework.",
    ),
    f(0, "Cargo.lock", "10 KB", "# auto-generated by cargo"),
];

/// The explorer's caller-owned state.
#[derive(Debug)]
pub(crate) struct State {
    sel: usize,
    expanded: [bool; TREE.len()],
}

impl State {
    /// Top-level dirs open so the tree is non-trivial at first paint.
    pub(crate) fn new() -> Self {
        let mut expanded = [false; TREE.len()];
        for (i, n) in TREE.iter().enumerate() {
            if n.dir && n.depth <= 1 {
                expanded[i] = true;
            }
        }
        Self { sel: 0, expanded }
    }

    /// Indices of the visible rows (collapsed folders hide their subtree).
    fn visible(&self) -> Vec<usize> {
        let mut out = Vec::new();
        let mut hide: Option<u16> = None;
        for (i, n) in TREE.iter().enumerate() {
            if let Some(dp) = hide {
                if n.depth > dp {
                    continue;
                }
                hide = None;
            }
            out.push(i);
            if n.dir && !self.expanded[i] {
                hide = Some(n.depth);
            }
        }
        out
    }

    /// `↑/↓` select, `Enter` expand-folder / open-file, `←` collapses or
    /// falls back to the rail.
    pub(crate) fn on_key(&mut self, code: KeyCode) -> ScreenOutcome {
        let vis = self.visible();
        match code {
            KeyCode::Up => self.sel = self.sel.saturating_sub(1),
            KeyCode::Down => self.sel = (self.sel + 1).min(vis.len() - 1),
            KeyCode::Enter | KeyCode::Right => {
                let n = vis[self.sel];
                if TREE[n].dir {
                    self.expanded[n] = !self.expanded[n];
                } else {
                    return ScreenOutcome::with_toast(
                        crate::screens::ToastLevel::Info,
                        format!("Open {}", TREE[n].name),
                    );
                }
            }
            KeyCode::Left => {
                let n = vis[self.sel];
                if TREE[n].dir && self.expanded[n] {
                    self.expanded[n] = false;
                } else {
                    return ScreenOutcome::ignored();
                }
            }
            _ => return ScreenOutcome::ignored(),
        }
        ScreenOutcome::consumed()
    }

    /// Click a tree row to select it (mirrors the `view` tree pane).
    pub(crate) fn on_click(&mut self, pos: Position, content: Rect) -> ScreenOutcome {
        let [tree_a, _right] =
            Layout::horizontal([Constraint::Percentage(42), Constraint::Fill(1)]).areas(content);
        let tin = tree_a.inner(Margin::new(1, 1));
        if tin.contains(pos) {
            let vis = self.visible();
            let i = (pos.y - tin.y) as usize;
            if i < vis.len() {
                self.sel = i;
                return ScreenOutcome::consumed();
            }
        }
        ScreenOutcome::ignored()
    }

    /// Draw the explorer.
    pub(crate) fn view(&self, theme: &Theme, _tick: u64, frame: &mut Frame<'_>, area: Rect) {
        let vis = self.visible();
        let sel = self.sel.min(vis.len() - 1);
        let node = &TREE[vis[sel]];

        let [tree_a, right] =
            Layout::horizontal([Constraint::Percentage(42), Constraint::Fill(1)]).areas(area);

        let items: Vec<TreeItem> = vis
            .iter()
            .map(|&i| {
                let n = &TREE[i];
                let label = if n.dir {
                    format!("{} {}/", if self.expanded[i] { '▾' } else { '▸' }, n.name)
                } else {
                    format!("  {}", n.name)
                };
                TreeItem::new(n.depth, label).expandable(n.dir && self.expanded[i])
            })
            .collect();
        frame.render_widget(
            Tree::new(items)
                .selected(Some(sel))
                .highlight_symbol("▌")
                .highlight_style(theme.selection())
                .style(theme.body())
                .block(framed(theme, "Explorer")),
            tree_a,
        );

        let [crumb, preview, foot] = Layout::vertical([
            Constraint::Length(1),
            Constraint::Fill(1),
            Constraint::Length(1),
        ])
        .areas(right);

        // Path breadcrumb built from the selected node's ancestry.
        let mut path: Vec<Line> = Vec::new();
        let mut want = node.depth;
        for &i in vis[..=sel].iter().rev() {
            if TREE[i].depth == want {
                path.push(Line::from(TREE[i].name.to_string()));
                if want == 0 {
                    break;
                }
                want -= 1;
            }
        }
        path.reverse();
        frame.render_widget(
            Breadcrumb::new(&path)
                .separator('/')
                .style(theme.caption())
                .emphasis_style(theme.accent_text()),
            crumb,
        );

        let pblock = framed(theme, if node.dir { "Folder" } else { node.name });
        let pin = pblock.inner(preview);
        frame.render_widget(pblock, preview);
        if node.dir {
            let children = vis
                .iter()
                .filter(|&&i| TREE[i].depth == node.depth + 1)
                .count();
            frame.render_widget(
                DescriptionList::new([
                    DescriptionRow::new("Type", "directory".to_string()),
                    DescriptionRow::new("Name", node.name.to_string()),
                    DescriptionRow::new("Depth", node.depth.to_string()),
                    DescriptionRow::new("Shown children", children.to_string()),
                ])
                .key_style(theme.caption())
                .value_style(theme.body())
                .style(theme.body()),
                pin,
            );
        } else {
            frame.render_widget(
                Paragraph::new(node.body)
                    .wrap(Wrap { trim: false })
                    .style(theme.body()),
                pin,
            );
        }

        frame.render_widget(
            StatusBar::new()
                .left(
                    Line::from(format!(" {} ", if node.dir { "dir" } else { "file" }))
                        .style(theme.caption()),
                )
                .center(
                    Line::from("↑↓ select · Enter open/expand · ← collapse").style(theme.caption()),
                )
                .right(Line::from(format!(" {} ", node.size)).style(theme.caption()))
                .style(Style::new().fg(theme.dim).bg(theme.raised)),
            foot,
        );
    }
}

/// A plain rounded panel.
fn framed(theme: &Theme, title: &str) -> Block<'static> {
    Block::bordered()
        .border_type(BorderType::Rounded)
        .title(Line::from(format!(" {title} ")).style(theme.caption()))
        .border_style(theme.border())
        .style(theme.body())
}
